export const CURRENT_CAMPAIGN_VERSION = "chery-2026-09";

export const PLACEHOLDER_COLORS = [
  { name: "Black", hex_code: "#121212" },
  { name: "Pearl White", hex_code: "#F2F2EE" },
  { name: "Champagne", hex_code: "#C9A07F" },
] as const;

export const CAMPAIGN_CARS = [
  {
    slug: "chery-arrizo-8-phev-2026",
    brand: "Chery",
    name: "Arrizo 8 PHEV",
    model: "Arrizo 8 PHEV",
    displayName: "Chery Arrizo 8 PHEV 2026",
    year: 2026,
    price: 79900,
    currency: "AED",
    priceLabel: "Starting from",
    bodyType: "Sedan",
    transmission: "Automatic",
    description:
      "A modern premium sedan combining efficient plug-in hybrid performance, comfort and contemporary design.",
    specs: ["Sedan", "2026", "Automatic", "Plug-in Hybrid"],
    sortOrder: 1,
  },
  {
    slug: "chery-tiggo-8-2026",
    brand: "Chery",
    name: "Tiggo 8",
    model: "Tiggo 8",
    displayName: "Chery Tiggo 8 2026",
    year: 2026,
    price: 90000,
    currency: "AED",
    priceLabel: "Starting from",
    bodyType: "SUV",
    transmission: "Automatic",
    description:
      "A spacious SUV designed for comfortable family driving with a modern interior and practical everyday performance.",
    specs: ["SUV", "2026", "Automatic", "Family SUV"],
    sortOrder: 2,
  },
  {
    slug: "chery-tiggo-4-2026",
    brand: "Chery",
    name: "Tiggo 4",
    model: "Tiggo 4",
    displayName: "Chery Tiggo 4 2026",
    year: 2026,
    price: 57000,
    currency: "AED",
    priceLabel: "Starting from",
    bodyType: "SUV",
    transmission: "Automatic",
    description: "A compact SUV offering practical everyday usability, modern styling and strong value.",
    specs: ["SUV", "2026", "Automatic", "Compact SUV"],
    sortOrder: 3,
  },
  {
    slug: "chery-tiggo-7-luxury-2026",
    brand: "Chery",
    name: "Tiggo 7 Luxury",
    model: "Tiggo 7 Luxury",
    displayName: "Chery Tiggo 7 Luxury 2026",
    year: 2026,
    price: 78999,
    currency: "AED",
    priceLabel: "Starting from",
    bodyType: "SUV",
    transmission: "Automatic",
    description: "A stylish SUV with a premium feel, modern technology and a comfortable driving experience.",
    specs: ["SUV", "2026", "Automatic", "Luxury Trim"],
    sortOrder: 4,
  },
] as const;
